### Numpy<br>
Library to work on array and matrices

In [1]:
import numpy as np

In [ ]:
arr1 = np.array([1,2,3,4])
print(type(arr1))
print(arr1.shape)

<class 'numpy.ndarray'>
(4,)


In [10]:
# reshape
arr1 = arr1.reshape(1,4)
print(arr1.shape)
print(arr1)
print('No of dimensions',arr1.ndim)

(1, 4)
[[1 2 3 4]]
No of dimensions 2


In [ ]:
# arange(start, end, steps)
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [8]:
# create identity matrix - diagonal ele 1
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**array attributes and functions**

In [13]:
# common attributes
arr2 = np.array([[3,6,1,9],[4,3,7,1]])

print("Array\n", arr2)
print("Shape\t", arr2.shape)
print("Number of dimensions\t", arr2.ndim)
print("Size (no of elements)\t", arr2.size)
print("Data Type\t", arr2.dtype)

Array
 [[3 6 1 9]
 [4 3 7 1]]
Shape	 (2, 4)
Number of dimensions	 2
Size (no of elements)	 8
Data Type	 int32


In [14]:
# vectorized operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print("Addition", arr1+arr2)    # same can be done for sub, mul, divide

Addition [11 22 33 44 55]


**math operation like *, -, +, / on array - works on all element and keep the dimensions intact**

In [30]:
np.array([1,2,3,4,5]) * 10

array([10, 20, 30, 40, 50])

In [33]:
b = np.array([1,2,3,4,5]).copy()
b

array([1, 2, 3, 4, 5])

In [16]:
# universal functions
arr = np.array([2,3,4,5,6])

print(np.sqrt(arr))

print(np.exp(arr))

print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


**array slicing and indexing**

In [18]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
print(arr[0][0])
print("\n",arr[1:,2:])
print("\n",arr[:2, :3])      # in slicind last value is excluded

1

 [[ 7  8]
 [11 12]]

 [[1 2 3]
 [5 6 7]]


In [27]:
# modify
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [28]:
arr[:2 , 2:] = [[17,18],[19,20]]
print(arr)

[[100   2  17  18]
 [  5   6  19  20]
 [  9  10  11  12]]


In [29]:
arr[1:] = 200
print(arr)

[[100   2  17  18]
 [200 200 200 200]
 [200 200 200 200]]


In [34]:
# statistical concept - normalization
# to have mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

# calculate means and standard deviation
mean = np.mean(data)
std_dev = np.std(data)
print(mean)
print(std_dev)

# normalize the data
normalized_data = (data - mean)/std_dev
print("Normalized Data:", normalized_data)

3.0
1.4142135623730951
Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [40]:
# logical operation
data = np.array([1,2,8,4,5,6,7,3,0])
print(data > 5)
print(data[data>5])
print(data[(data>=5) & (data<8)])

[False False  True False False  True  True False False]
[8 6 7]
[5 6 7]
